# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170612_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 12, 3, 35, 3, 147396, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='postlike',
            table=None,
        ),
    ]
