# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20170612_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 12, 4, 53, 25, 207111, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='commentlike',
            table=None,
        ),
    ]
